name: Check Black

on: [push]

jobs:
  run_black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.1"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check the code using Black
      run: |
        black --check .
